. ~/bin/dotfiles/bash/env
. ~/bin/dotfiles/bash/config
. ~/bin/dotfiles/bash/aliases
. ~/bin/dotfiles/bash/updaters
. ~/bin/dotfiles/bash/prompt
[ -f ~/bin/dotfiles/bash/secrets ] && . ~/bin/dotfiles/bash/secrets
